# -*- coding: utf-8 -*-
"""Functional-programming.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FaXQwk18T2SA12SqF9w46VzBF6uZoIQs
"""



"""# `filter()`

## 1. Filter even numbers

```python
nums = [1, 2, 3, 4, 5, 6]

evens = list(filter(lambda x: x % 2 == 0, nums))

print(evens)
# [2, 4, 6]
```

---

## 2. Filter strings by length

```python
words = ["hi", "python", "ai", "development"]

long_words = list(filter(lambda w: len(w) > 4, words))

print(long_words)
# ['python', 'development']
```

---

## 3. Remove empty strings

```python
data = ["hello", "", "world", "", "python"]

cleaned = list(filter(None, data))

print(cleaned)
# ['hello', 'world', 'python']
```

---

## 4. Filter prime numbers

```python
def is_prime(n):
    if n < 2:
        return False

    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False

    return True


nums = range(1, 30)

primes = list(filter(is_prime, nums))

print(primes)
```

---

## 5. Filter dictionaries

```python
employees = [
    {"name": "Alice", "salary": 50000},
    {"name": "Bob", "salary": 90000},
    {"name": "Charlie", "salary": 70000},
]

high_salary = list(filter(lambda e: e["salary"] > 60000, employees))

print(high_salary)
```

---

## 6. Filter vowels

```python
text = "artificial intelligence"

vowels = list(filter(lambda ch: ch in "aeiou", text))

print(vowels)
```

---

## 7. Filter positive numbers

```python
nums = [-5, 3, -1, 9, 0]

positive = list(filter(lambda x: x > 0, nums))

print(positive)
```

---

## 8. Filter valid emails

```python
emails = [
    "abc@gmail.com",
    "wrongmail",
    "hello@yahoo.com"
]

valid = list(filter(lambda e: "@" in e, emails))

print(valid)
```

---

## 9. Filter students who passed

```python
marks = [34, 55, 90, 23, 67]

passed = list(filter(lambda x: x >= 40, marks))

print(passed)
```

---

## 10. Filter unique objects

```python
nums = [1, 2, 2, 3, 4, 4, 5]

seen = set()

unique = list(filter(lambda x: not (x in seen or seen.add(x)), nums))

print(unique)
```

---

## 11. Filter based on multiple conditions

```python
nums = [5, 12, 18, 25, 30]

result = list(filter(lambda x: x % 2 == 0 and x > 15, nums))

print(result)
# [18, 30]
```

---

## 12. Filter files by extension

```python
files = ["a.txt", "b.py", "c.java", "d.py"]

python_files = list(filter(lambda f: f.endswith(".py"), files))

print(python_files)
```

---

## 13. Filter truthy values

```python
values = [0, 1, "", "hello", [], [1, 2], None]

truthy = list(filter(bool, values))

print(truthy)
```

---

## 14. Filter odd numbers

```python
nums = [1, 2, 3, 4, 5]

odds = list(filter(lambda x: x % 2 != 0, nums))

print(odds)
```

---

## 15. Filter names starting with A

```python
names = ["Alice", "Bob", "Andrew", "Charlie"]

result = list(filter(lambda n: n.startswith("A"), names))

print(result)
```

---

# `lambda`

## 1. Simple addition

```python
add = lambda a, b: a + b

print(add(2, 3))
```

---

## 2. Square a number

```python
square = lambda x: x * x

print(square(5))
```

---

## 3. Sort tuples by second value

```python
data = [(1, 5), (2, 1), (3, 3)]

sorted_data = sorted(data, key=lambda x: x[1])

print(sorted_data)
```

---

## 4. Find max using lambda

```python
nums = [1, 8, 3, 10]

largest = max(nums, key=lambda x: x)

print(largest)
```

---

## 5. Convert to uppercase

```python
upper = lambda s: s.upper()

print(upper("python"))
```

---

## 6. Check even/odd

```python
is_even = lambda x: x % 2 == 0

print(is_even(10))
```

---

## 7. Lambda inside function

```python
def multiplier(n):
    return lambda x: x * n

double = multiplier(2)

print(double(10))
```

---

## 8. Sort dictionary list

```python
students = [
    {"name": "A", "marks": 90},
    {"name": "B", "marks": 70},
]

sorted_students = sorted(students, key=lambda s: s["marks"])

print(sorted_students)
```

---

## 9. Reverse string

```python
reverse = lambda s: s[::-1]

print(reverse("python"))
```

---

## 10. Conditional lambda

```python
check = lambda x: "Positive" if x > 0 else "Negative"

print(check(-5))
```

---

## 11. Multiple arguments

```python
calc = lambda a, b, c: a + b * c

print(calc(2, 3, 4))
```

---

## 12. Lambda with map

```python
nums = [1, 2, 3]

result = list(map(lambda x: x * 10, nums))

print(result)
```

---

## 13. Lambda with filter

```python
nums = [1, 2, 3, 4]

evens = list(filter(lambda x: x % 2 == 0, nums))

print(evens)
```

---

## 14. Lambda with reduce

```python
from functools import reduce

nums = [1, 2, 3, 4]

sum_all = reduce(lambda a, b: a + b, nums)

print(sum_all)
```

---

## 15. Nested lambda

```python
add = lambda x: lambda y: x + y

result = add(10)(5)

print(result)
```

---

# `map()`

## 1. Square all numbers

```python
nums = [1, 2, 3, 4]

squares = list(map(lambda x: x**2, nums))

print(squares)
```

---

## 2. Convert to uppercase

```python
names = ["alice", "bob"]

upper = list(map(str.upper, names))

print(upper)
```

---

## 3. Convert strings to int

```python
nums = ["1", "2", "3"]

ints = list(map(int, nums))

print(ints)
```

---

## 4. Add two lists

```python
a = [1, 2, 3]
b = [4, 5, 6]

result = list(map(lambda x, y: x + y, a, b))

print(result)
```

---

## 5. Extract lengths

```python
words = ["python", "ai", "ml"]

lengths = list(map(len, words))

print(lengths)
```

---

## 6. Celsius to Fahrenheit

```python
temps = [0, 20, 37]

fahrenheit = list(map(lambda c: (c * 9/5) + 32, temps))

print(fahrenheit)
```

---

## 7. Get dictionary values

```python
students = [
    {"name": "A"},
    {"name": "B"}
]

names = list(map(lambda s: s["name"], students))

print(names)
```

---

## 8. Remove whitespace

```python
words = ["  hello ", " python  "]

cleaned = list(map(str.strip, words))

print(cleaned)
```

---

## 9. Convert numbers to strings

```python
nums = [1, 2, 3]

result = list(map(str, nums))

print(result)
```

---

## 10. Multiply all numbers

```python
nums = [1, 2, 3]

result = list(map(lambda x: x * 100, nums))

print(result)
```

---

## 11. Capitalize names

```python
names = ["alice", "bob"]

result = list(map(str.capitalize, names))

print(result)
```

---

## 12. Extract first character

```python
words = ["python", "java"]

result = list(map(lambda w: w[0], words))

print(result)
```

---

## 13. Boolean mapping

```python
nums = [0, 1, 2, 0]

result = list(map(bool, nums))

print(result)
```

---

## 14. Round decimals

```python
nums = [1.234, 5.678]

rounded = list(map(lambda x: round(x, 1), nums))

print(rounded)
```

---

## 15. Pair concatenation

```python
first = ["John", "Jane"]
last = ["Doe", "Smith"]

full = list(map(lambda f, l: f + " " + l, first, last))

print(full)
```

---

# `functools`

```python
from functools import reduce, partial, lru_cache
```

## 1. Reduce sum

```python
from functools import reduce

nums = [1, 2, 3, 4]

result = reduce(lambda a, b: a + b, nums)

print(result)
```

---

## 2. Reduce multiplication

```python
from functools import reduce

nums = [1, 2, 3, 4]

product = reduce(lambda a, b: a * b, nums)

print(product)
```

---

## 3. Partial function

```python
from functools import partial

def power(base, exp):
    return base ** exp

square = partial(power, exp=2)

print(square(5))
```

---

## 4. Partial with greeting

```python
from functools import partial

def greet(greeting, name):
    return f"{greeting}, {name}"

hello = partial(greet, "Hello")

print(hello("Alice"))
```

---

## 5. LRU cache Fibonacci

```python
from functools import lru_cache

@lru_cache(maxsize=None)
def fib(n):
    if n < 2:
        return n
    return fib(n-1) + fib(n-2)

print(fib(40))
```

---

## 6. Total salary

```python
from functools import reduce

salaries = [5000, 7000, 8000]

total = reduce(lambda a, b: a + b, salaries)

print(total)
```

---

## 7. Find maximum

```python
from functools import reduce

nums = [10, 50, 30]

largest = reduce(lambda a, b: a if a > b else b, nums)

print(largest)
```

---

## 8. Accumulate string

```python
from functools import reduce

words = ["Python", "is", "awesome"]

sentence = reduce(lambda a, b: a + " " + b, words)

print(sentence)
```

---

## 9. Cache API simulation

```python
from functools import lru_cache
import time

@lru_cache(maxsize=3)
def fetch_data(x):
    time.sleep(2)
    return x * 10

print(fetch_data(5))
print(fetch_data(5))
```

---

## 10. Custom sort with cmp_to_key

```python
from functools import cmp_to_key

def compare(a, b):
    return len(a) - len(b)

words = ["apple", "kiwi", "banana"]

sorted_words = sorted(words, key=cmp_to_key(compare))

print(sorted_words)
```

---

# Iterators

## 1. Basic iterator

```python
nums = [1, 2, 3]

it = iter(nums)

print(next(it))
print(next(it))
```

---

## 2. Custom iterator

```python
class Counter:
    def __init__(self, limit):
        self.limit = limit
        self.current = 0

    def __iter__(self):
        return self

    def __next__(self):
        if self.current >= self.limit:
            raise StopIteration

        self.current += 1
        return self.current


for x in Counter(5):
    print(x)
```

---

## 3. Reverse iterator

```python
nums = [1, 2, 3]

it = reversed(nums)

print(next(it))
```

---

## 4. Infinite iterator

```python
class Infinite:
    def __iter__(self):
        return self

    def __next__(self):
        return 1

it = Infinite()

print(next(it))
```

---

## 5. File iterator

```python
with open("test.txt") as f:
    for line in f:
        print(line.strip())
```

---

## 6. Enumerate iterator

```python
names = ["A", "B", "C"]

for idx, val in enumerate(names):
    print(idx, val)
```

---

## 7. Zip iterator

```python
a = [1, 2]
b = ["x", "y"]

for pair in zip(a, b):
    print(pair)
```

---

## 8. Iterator exhaustion

```python
nums = iter([1, 2])

print(next(nums))
print(next(nums))

# next(nums) -> StopIteration
```

---

## 9. Iterator expression

```python
nums = iter(range(5))

for n in nums:
    print(n)
```

---

## 10. Custom alphabet iterator

```python
class Alphabet:
    def __init__(self):
        self.char = ord('a')

    def __iter__(self):
        return self

    def __next__(self):
        if self.char > ord('z'):
            raise StopIteration

        ch = chr(self.char)
        self.char += 1
        return ch


for c in Alphabet():
    print(c)
```

---

# Generators

## 1. Simple generator

```python
def gen():
    yield 1
    yield 2
    yield 3

for x in gen():
    print(x)
```

---

## 2. Generator expression

```python
squares = (x*x for x in range(5))

print(next(squares))
```

---

## 3. Fibonacci generator

```python
def fib(n):
    a, b = 0, 1

    for _ in range(n):
        yield a
        a, b = b, a + b

for x in fib(10):
    print(x)
```

---

## 4. Infinite generator

```python
def infinite():
    n = 1

    while True:
        yield n
        n += 1
```

---

## 5. Read large file

```python
def read_file(path):
    with open(path) as f:
        for line in f:
            yield line.strip()
```

---

## 6. Countdown generator

```python
def countdown(n):
    while n > 0:
        yield n
        n -= 1

for x in countdown(5):
    print(x)
```

---

## 7. Yield from

```python
def gen1():
    yield from [1, 2, 3]

print(list(gen1()))
```

---

## 8. Pipeline generator

```python
def even(nums):
    for n in nums:
        if n % 2 == 0:
            yield n

def square(nums):
    for n in nums:
        yield n * n

result = square(even(range(10)))

print(list(result))
```

---

## 9. Generator with send()

```python
def echo():
    while True:
        value = yield
        print(value)

g = echo()

next(g)

g.send("hello")
```

---

## 10. Lazy evaluation

```python
def lazy():
    print("Start")
    yield 1
    print("Middle")
    yield 2

g = lazy()

print(next(g))
print(next(g))
```

---

# Decorators

## 1. Basic decorator

```python
def decorator(func):
    def wrapper():
        print("Before")
        func()
        print("After")
    return wrapper


@decorator
def hello():
    print("Hello")


hello()
```

---

## 2. Timing decorator

```python
import time

def timer(func):
    def wrapper():
        start = time.time()

        func()

        end = time.time()

        print(end - start)

    return wrapper
```

---

## 3. Logging decorator

```python
def logger(func):
    def wrapper(*args, **kwargs):
        print(f"Calling {func.__name__}")

        return func(*args, **kwargs)

    return wrapper
```

---

## 4. Authentication decorator

```python
def auth(func):
    def wrapper(user):
        if user != "admin":
            return "Access denied"

        return func(user)

    return wrapper
```

---

## 5. Retry decorator

```python
def retry(func):
    def wrapper():
        for _ in range(3):
            try:
                return func()
            except:
                print("Retrying...")
    return wrapper
```

---

## 6. Memoization decorator

```python
def memoize(func):
    cache = {}

    def wrapper(n):
        if n in cache:
            return cache[n]

        cache[n] = func(n)

        return cache[n]

    return wrapper
```

---

## 7. Decorator with arguments

```python
def repeat(times):
    def decorator(func):
        def wrapper():
            for _ in range(times):
                func()

        return wrapper

    return decorator


@repeat(3)
def hello():
    print("Hello")
```

---

## 8. Preserve metadata

```python
from functools import wraps

def decorator(func):
    @wraps(func)
    def wrapper():
        return func()

    return wrapper
```

---

## 9. Class decorator

```python
def add_method(cls):
    cls.new_method = lambda self: "Hello"

    return cls


@add_method
class Test:
    pass


t = Test()

print(t.new_method())
```

---

## 10. Singleton decorator

```python
def singleton(cls):
    instances = {}

    def wrapper():
        if cls not in instances:
            instances[cls] = cls()

        return instances[cls]

    return wrapper
```

"""